# Generated by Django 4.1.6 on 2023-05-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
