# Generated by Django 4.1.6 on 2023-05-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.SmallIntegerField(verbose_name='Cantidad')),
                ('tipo_isumo', models.CharField(choices=[('', '-----------'), ('1', 'Alimento'), ('2', 'Limpieza')], max_length=1)),
                ('unidad_de_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('LT', 'Litros'), ('UN', 'Unidades')], max_length=2)),
            ],
        ),
    ]
