# Generated by Django 4.1.6 on 2023-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='tipo_isumo',
            field=models.CharField(choices=[('1', 'Alimento'), ('', '-----------'), ('2', 'Limpieza')], max_length=1),
        ),
    ]
